# Generated by Django 5.2.8 on 2025-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_booking_status_testreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_images/'),
        ),
    ]
