# Generated by Django 5.2.8 on 2025-12-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='pending@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
